flowchart TD

ENV
BOOTSTRAP
CREATEAPP
CREATEDB

PGLITE
POSTGRES
TESTCONTAINER

DB
MODULES
DOMAIN

ENV --> BOOTSTRAP
BOOTSTRAP --> CREATEAPP
CREATEAPP --> CREATEDB

CREATEDB --> PGLITE
CREATEDB --> POSTGRES
CREATEDB --> TESTCONTAINER

PGLITE --> DB
POSTGRES --> DB
TESTCONTAINER --> DB

DB --> MODULES
MODULES --> DOMAIN