services:
  test-db:
    image: postgres:16-alpine
    container_name: nextjs16_test_db
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_test
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d app_test']
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - nextjs16_test_db_data:/var/lib/postgresql/data

volumes:
  nextjs16_test_db_data:
