import react from '@vitejs/plugin-react';
import tsconfigPaths from 'vite-tsconfig-paths';
import { defineConfig } from 'vitest/config';

export default defineConfig({
  plugins: [react(), tsconfigPaths()],
  test: {
    name: 'unit',
    environment: 'jsdom',
    globals: true,
    pool: 'forks',
    maxWorkers: 4,
    hookTimeout: 30_000,
    setupFiles: ['./tests/setup.tsx', './tests/polyfills.ts'],
    include: [
      'src/**/*.test.{ts,tsx}',
      'scripts/**/*.test.{ts,tsx}',
      // Pure-function unit tests for E2E support helpers (e.g.
      // e2e/support/csp-violations.ts) -- these are plain TypeScript, not
      // Playwright specs (those stay e2e/**/*.spec.ts per this repo's
      // convention), so they belong in the unit runner, not a browser.
      'e2e/**/*.test.{ts,tsx}',
    ],
    exclude: [
      'src/**/*.integration.test.{ts,tsx}',
      'src/**/*.db.test.{ts,tsx}',
      'scripts/**/*.db.test.{ts,tsx}',
      'src/stories/**',
      'src/core/db/migrations/**',
    ],
    coverage: {
      enabled: true,
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
      reportsDirectory: './coverage/unit',
      include: ['src/**/*.{ts,tsx}', 'scripts/**/*.{ts,tsx}'],
      exclude: [
        'src/app/**',
        'src/instrumentation.ts',
        'src/instrumentation-client.ts',
        '**/*.d.ts',
        '**/*.test.{ts,tsx}',
        '**/*.integration.test.{ts,tsx}',
        '**/tests/**',
        '**/__tests__/**',
        '**/mocks/**',
        '**/*.mock.ts',
        'src/testing/**',
        'src/features/security-showcase/**',
        'src/features/feature-flags-showcase/components/**',
        'src/**/*.stories.{ts,tsx}',
        'src/**/types.{ts,tsx}',
        'src/**/types/**',
        'src/**/index.{ts,tsx}',
        'src/stories/**',
        'src/core/db/**',
        'src/core/observability/better-stack-web-vitals.tsx',
        'src/core/observability/new-relic.ts',
        'src/modules/authorization/infrastructure/drizzle/schema.ts',
        'src/modules/feature-flags/infrastructure/drizzle/schema.ts',
        'src/modules/user/infrastructure/drizzle/schema.ts',
        'src/modules/billing/infrastructure/drizzle/schema.ts',
        'src/modules/provisioning/infrastructure/drizzle/schema.ts',
        'src/modules/auth/infrastructure/drizzle/schema.ts',
        'src/modules/waitlist/domain/WaitlistRepository.ts',
        'src/modules/waitlist/domain/WaitlistService.ts',
        'src/modules/auth/infrastructure/ExternalIdentityMapper.ts',
        'src/modules/auth/infrastructure/InternalIdentityLookup.ts',
        'src/modules/authorization/infrastructure/MockRepositories.ts',
        'src/modules/billing/domain/BillingService.ts',
        'src/modules/billing/domain/SubscriptionStatus.ts',
        'src/modules/billing/infrastructure/drizzle/seed.ts',
        'src/modules/billing/infrastructure/stripe/StripeBillingService.ts',
        'src/modules/invitations/domain/EmailService.ts',
        'src/modules/invitations/domain/InvitationRepository.ts',
        'src/modules/invitations/domain/InvitationService.ts',
        'src/modules/provisioning/domain/repositories/**',
        'src/modules/**/infrastructure/drizzle/Drizzle*.ts',
        'src/modules/**/infrastructure/drizzle/seed.ts',
        'scripts/bootstrap-admin.ts',
        'scripts/db-migrate-prod.ts',
        'scripts/flags/**',
        'scripts/leantime/**',
        'scripts/new-relic/**',
        'scripts/lib/**',
        'scripts/db-seed.ts',
        'src/core/contracts/**',
        '**/__mocks__/**',
        'src/security/core/security-dependencies.ts',
        'src/modules/provisioning/domain/tenancy-mode.ts',
        'src/modules/authorization/domain/permission.ts',
      ],
      clean: true,
      cleanOnRerun: true,
      thresholds: {
        lines: 70,
        functions: 70,
        branches: 70,
        statements: 70,
      },
    },
  },
});
