import react from '@vitejs/plugin-react';
import tsconfigPaths from 'vite-tsconfig-paths';
import { defineConfig } from 'vitest/config';

export default defineConfig({
  plugins: [react(), tsconfigPaths()],
  test: {
    name: 'unit',
    environment: 'jsdom',
    globals: true,
    hookTimeout: 30_000,
    setupFiles: ['./tests/setup.tsx', './tests/polyfills.ts'],
    include: ['src/**/*.test.{ts,tsx}', 'scripts/**/*.test.{ts,tsx}'],
    exclude: [
      'src/**/*.integration.test.{ts,tsx}',
      'src/stories/**',
      'src/core/db/migrations/**',
    ],
    coverage: {
      enabled: true,
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
      reportsDirectory: './coverage/unit',
      include: ['src/**/*.{ts,tsx}', 'scripts/**/*.{ts,tsx}'],
      exclude: [
        'src/app/**',
        '**/*.d.ts',
        '**/*.test.{ts,tsx}',
        '**/*.integration.test.{ts,tsx}',
        '**/tests/**',
        '**/__tests__/**',
        '**/mocks/**',
        '**/*.mock.ts',
        'src/testing/**',
        'src/features/security-showcase/**',
        'src/**/*.stories.{ts,tsx}',
        'src/**/types.{ts,tsx}',
        'src/**/types/**',
        'src/**/index.{ts,tsx}',
        'src/stories/**',
        'src/core/db/**',
        'src/modules/authorization/infrastructure/drizzle/schema.ts',
        'src/modules/feature-flags/infrastructure/drizzle/schema.ts',
        'src/modules/user/infrastructure/drizzle/schema.ts',
        'src/modules/billing/infrastructure/drizzle/schema.ts',
        'src/modules/provisioning/infrastructure/drizzle/schema.ts',
        'src/modules/auth/infrastructure/drizzle/schema.ts',
        'scripts/flags/**',
        'scripts/leantime/**',
        'scripts/new-relic/**',
        'scripts/lib/**',
        'scripts/db-seed.ts',
        'src/core/contracts/**',
        'src/security/core/security-dependencies.ts',
        'src/modules/provisioning/domain/tenancy-mode.ts',
        'src/modules/authorization/domain/permission.ts',
      ],
      clean: true,
      cleanOnRerun: true,
      thresholds: {
        lines: 70,
        functions: 70,
        branches: 70,
        statements: 70,
      },
    },
  },
});
