// @vitest-environment node

import { mkdtemp, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';

import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import {
  joinRemotePath,
  listPluginFiles,
  resolveDeployConfig,
  sha256File,
} from './deploy-plugin';

describe('leantime plugin deploy helpers', () => {
  const originalEnv = { ...process.env };

  beforeEach(() => {
    process.env = { ...originalEnv };
  });

  afterEach(() => {
    process.env = { ...originalEnv };
  });

  it('normalizes remote path joins without allowing shell separators', () => {
    expect(
      joinRemotePath(
        'domains/leantime.wmitrus.useruno.com/public_html/leantime/',
        '/app/',
        'Plugins',
        'AutomationApi',
      ),
    ).toBe(
      'domains/leantime.wmitrus.useruno.com/public_html/leantime/app/Plugins/AutomationApi',
    );
  });

  it('resolves production deploy config from dedicated Leantime env vars', () => {
    process.env.LEANTIME_DEPLOY_HOST = 's2.hostuno.com';
    process.env.LEANTIME_DEPLOY_USER = 'wmitrus';
    process.env.LEANTIME_DEPLOY_ROOT =
      'domains/leantime.wmitrus.useruno.com/public_html/leantime';
    process.env.LEANTIME_PLUGIN_SOURCE_DIR = 'leantime-plugins/AutomationApi';

    const config = resolveDeployConfig();

    expect(config.host).toBe('s2.hostuno.com');
    expect(config.user).toBe('wmitrus');
    expect(config.pluginName).toBe('AutomationApi');
    expect(config.backupRoot).toBe(
      'domains/leantime.wmitrus.useruno.com/public_html/leantime/storage/plugin-backups',
    );
    expect(config.remoteStagingRoot).toBe(
      'domains/leantime.wmitrus.useruno.com/public_html/leantime/storage/plugin-deploy-staging',
    );
  });

  it('rejects unsafe remote deploy paths', () => {
    process.env.LEANTIME_DEPLOY_HOST = 's2.hostuno.com';
    process.env.LEANTIME_DEPLOY_USER = 'wmitrus';
    process.env.LEANTIME_DEPLOY_ROOT = '../leantime';

    expect(() => resolveDeployConfig()).toThrow(
      'LEANTIME_DEPLOY_ROOT contains unsupported path characters.',
    );
  });

  it('lists plugin files with sha256 hashes', async () => {
    const dir = await mkdtemp(path.join(os.tmpdir(), 'lt-plugin-'));

    try {
      const pluginFilePath = path.join(dir, 'register.php');
      // eslint-disable-next-line security/detect-non-literal-fs-filename -- test temp path is generated by mkdtemp and confined to this test case
      await writeFile(pluginFilePath, '<?php\n', 'utf8');
      const files = await listPluginFiles(dir);
      const hash = await sha256File(pluginFilePath, dir);

      expect(files).toEqual([
        {
          hash,
          localPath: path.join(dir, 'register.php'),
          relativePath: 'register.php',
          size: 6,
        },
      ]);
    } finally {
      await rm(dir, { force: true, recursive: true });
    }
  });
});
