flowchart TD

subgraph OUTER
    UI
    INFRA
end

subgraph INNER
    APPLICATION
    DOMAIN
end

CONTRACTS

UI --> APPLICATION
APPLICATION --> DOMAIN
APPLICATION --> CONTRACTS
INFRA --> CONTRACTS
INFRA --> DOMAIN
CONTAINER --> INFRA

DOMAIN -.-> UI
DOMAIN -.-> INFRA
UI -.-> DOMAIN