flowchart TD

subgraph DELIVERY
APP
FEATURES
PROXY
end

subgraph APPLICATION
SECURITY
end

subgraph DOMAIN
MODULES
end

subgraph INFRASTRUCTURE
DB
AUTH_ADAPTER
end

subgraph CORE
CONTAINER
CONTRACTS
RUNTIME
end

APP --> FEATURES
APP --> PROXY
PROXY --> SECURITY
SECURITY --> MODULES
MODULES --> CONTRACTS

RUNTIME --> CONTAINER
CONTAINER --> MODULES
CONTAINER --> DB