flowchart TD

ENV
BOOTSTRAP
CREATEAPP
APPCONTAINER

REQUEST
CHILD

IDENTITY
TENANT
AUTHZ

DOMAIN
DB
RESPONSE

ENV --> BOOTSTRAP
BOOTSTRAP --> CREATEAPP
CREATEAPP --> APPCONTAINER

REQUEST --> CHILD
APPCONTAINER --> CHILD

CHILD --> IDENTITY
IDENTITY --> TENANT
TENANT --> AUTHZ
AUTHZ --> DOMAIN
DOMAIN --> DB
DOMAIN --> RESPONSE