import { ClerkProvider } from '@clerk/nextjs';
import { SpeedInsights } from '@vercel/speed-insights/next';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { Suspense } from 'react';

import { env } from '@/core/env';

import { GlobalErrorHandlers } from '@/shared/components/error/global-error-handlers';

import { HeaderWithAuth } from '@/modules/auth/ui/HeaderWithAuth';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function AppLayoutContent({ children }: { children: React.ReactNode }) {
  return (
    <>
      <HeaderWithAuth />
      <GlobalErrorHandlers />
      {(env.VERCEL_ENV === 'production' || env.VERCEL_ENV === 'preview') && (
        <SpeedInsights />
      )}
      {children}
    </>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isClerkProvider = env.AUTH_PROVIDER === 'clerk';

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Suspense fallback={null}>
          {isClerkProvider ? (
            <ClerkProvider
              signInUrl={env.NEXT_PUBLIC_CLERK_SIGN_IN_URL}
              signUpUrl={env.NEXT_PUBLIC_CLERK_SIGN_UP_URL}
              waitlistUrl={env.NEXT_PUBLIC_CLERK_WAITLIST_URL}
              signInFallbackRedirectUrl={
                env.NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL
              }
              signUpFallbackRedirectUrl={
                env.NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL
              }
              signInForceRedirectUrl={
                env.NEXT_PUBLIC_CLERK_SIGN_IN_FORCE_REDIRECT_URL
              }
              signUpForceRedirectUrl={
                env.NEXT_PUBLIC_CLERK_SIGN_UP_FORCE_REDIRECT_URL
              }
            >
              <AppLayoutContent>{children}</AppLayoutContent>
            </ClerkProvider>
          ) : (
            <AppLayoutContent>{children}</AppLayoutContent>
          )}
        </Suspense>
      </body>
    </html>
  );
}
