import { ClerkProvider } from '@clerk/nextjs';
import { SpeedInsights } from '@vercel/speed-insights/next';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import Script from 'next/script';
import { Suspense } from 'react';

import { env } from '@/core/env';
import { BetterStackWebVitalsProvider } from '@/core/observability/better-stack-web-vitals';
import {
  getNrBrowserCdnConfig,
  type NrBrowserCdnConfig,
} from '@/core/observability/new-relic-browser';

import { GlobalErrorHandlers } from '@/shared/components/error/global-error-handlers';

import { normalizeClerkPostAuthRedirect } from '@/modules/auth/lib/clerk-redirects';
import { SessionProvider } from '@/modules/auth/ui/authjs/SessionProvider';
import { HeaderWithAuth } from '@/modules/auth/ui/HeaderWithAuth';
import { getCspNonce } from '@/security/rsc/csp-nonce';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
  preload: false,
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function RootLayoutShell() {
  return (
    <header className="sticky top-0 z-50 w-full border-b border-zinc-200 bg-white/80 dark:border-zinc-800 dark:bg-black/80">
      <div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8">
        <div className="h-5 w-28 animate-pulse rounded bg-zinc-200 dark:bg-zinc-800" />
        <div className="h-9 w-20 animate-pulse rounded-full bg-zinc-100 dark:bg-zinc-800" />
      </div>
    </header>
  );
}

/**
 * Reads the CSP nonce and renders the New Relic browser bootstrap scripts.
 * A dedicated async Server Component so the dynamic-rendering cost of
 * getCspNonce() (see its doc comment) stays scoped to just this piece of
 * `<head>`, rather than making the whole RootLayout function dynamic.
 */
async function NrBrowserScripts({
  cdnConfig,
  isNewRelicApmBrowserEnabled,
}: {
  cdnConfig: NrBrowserCdnConfig | null;
  isNewRelicApmBrowserEnabled: boolean;
}) {
  const nonce = await getCspNonce();

  return (
    <>
      {cdnConfig && (
        <>
          <Script
            id="nr-browser-cdn-config"
            strategy="beforeInteractive"
            nonce={nonce}
            dangerouslySetInnerHTML={{
              __html: `window.NREUM||(NREUM={});NREUM.init=${JSON.stringify(cdnConfig.init)};NREUM.loader_config={accountID:${JSON.stringify(cdnConfig.accountId)},trustKey:${JSON.stringify(cdnConfig.accountId)},agentID:${JSON.stringify(cdnConfig.agentId)},licenseKey:${JSON.stringify(cdnConfig.licenseKey)},applicationID:${JSON.stringify(cdnConfig.applicationId)}};NREUM.info={beacon:${JSON.stringify(cdnConfig.beacon)},errorBeacon:${JSON.stringify(cdnConfig.beacon)},licenseKey:${JSON.stringify(cdnConfig.licenseKey)},applicationID:${JSON.stringify(cdnConfig.applicationId)},sa:1};`,
            }}
          />
          <Script
            id="nr-browser-cdn"
            src={cdnConfig.agentUrl}
            strategy="beforeInteractive"
            nonce={nonce}
          />
        </>
      )}
      {isNewRelicApmBrowserEnabled && !cdnConfig && (
        <Script
          id="nr-browser-agent"
          src="/observability/new-relic-browser.js"
          strategy="afterInteractive"
          nonce={nonce}
        />
      )}
    </>
  );
}

/**
 * Wraps ClerkProvider with the CSP nonce. Clerk's `nonce` prop requires
 * `dynamic` to also be set (it threads the nonce through to the
 * @clerk/clerk-js script tag for a strict-dynamic CSP — see Clerk's
 * ClerkProviderProps doc comment) — only pass `dynamic` when we actually
 * have a nonce to give it, so strict mode being off doesn't needlessly
 * force Clerk into dynamic rendering.
 */
async function ClerkProviderWithNonce({
  children,
  signInUrl,
  signUpUrl,
  waitlistUrl,
  signInFallbackRedirectUrl,
  signUpFallbackRedirectUrl,
  signInForceRedirectUrl,
  signUpForceRedirectUrl,
}: {
  children: React.ReactNode;
  signInUrl: string;
  signUpUrl: string;
  waitlistUrl: string;
  signInFallbackRedirectUrl: string | undefined;
  signUpFallbackRedirectUrl: string | undefined;
  signInForceRedirectUrl: string | undefined;
  signUpForceRedirectUrl: string | undefined;
}) {
  const nonce = await getCspNonce();

  return (
    <ClerkProvider
      nonce={nonce}
      dynamic={Boolean(nonce)}
      signInUrl={signInUrl}
      signUpUrl={signUpUrl}
      waitlistUrl={waitlistUrl}
      signInFallbackRedirectUrl={signInFallbackRedirectUrl}
      signUpFallbackRedirectUrl={signUpFallbackRedirectUrl}
      signInForceRedirectUrl={signInForceRedirectUrl}
      signUpForceRedirectUrl={signUpForceRedirectUrl}
    >
      {children}
    </ClerkProvider>
  );
}

function AppLayoutContent({ children }: { children: React.ReactNode }) {
  return (
    <>
      <HeaderWithAuth />
      <GlobalErrorHandlers />
      {(env.VERCEL_ENV === 'production' || env.VERCEL_ENV === 'preview') && (
        <SpeedInsights />
      )}
      {children}
    </>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isNewRelicApmBrowserEnabled =
    env.NEW_RELIC_ENABLED && Boolean(env.NEW_RELIC_LICENSE_KEY);
  const cdnConfig = getNrBrowserCdnConfig();
  const isBetterStackWebVitalsEnabled =
    env.BETTERSTACK_ENABLED && env.BETTERSTACK_WEB_VITALS_ENABLED;
  const isClerkProvider = env.AUTH_PROVIDER === 'clerk';
  const isAuthJsProvider = env.AUTH_PROVIDER === 'authjs';
  const signInFallbackRedirectUrl = normalizeClerkPostAuthRedirect(
    env.NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL,
    env.NEXT_PUBLIC_APP_URL,
  );
  const signUpFallbackRedirectUrl = normalizeClerkPostAuthRedirect(
    env.NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL,
    env.NEXT_PUBLIC_APP_URL,
  );
  const signInForceRedirectUrl = normalizeClerkPostAuthRedirect(
    env.NEXT_PUBLIC_CLERK_SIGN_IN_FORCE_REDIRECT_URL,
    env.NEXT_PUBLIC_APP_URL,
  );
  const signUpForceRedirectUrl = normalizeClerkPostAuthRedirect(
    env.NEXT_PUBLIC_CLERK_SIGN_UP_FORCE_REDIRECT_URL,
    env.NEXT_PUBLIC_APP_URL,
  );

  return (
    <html lang="en">
      <head>
        <NrBrowserScripts
          cdnConfig={cdnConfig}
          isNewRelicApmBrowserEnabled={isNewRelicApmBrowserEnabled}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {isBetterStackWebVitalsEnabled && (
          <Suspense fallback={null}>
            <BetterStackWebVitalsProvider />
          </Suspense>
        )}
        {isClerkProvider ? (
          <Suspense fallback={<RootLayoutShell />}>
            <ClerkProviderWithNonce
              signInUrl={env.NEXT_PUBLIC_CLERK_SIGN_IN_URL}
              signUpUrl={env.NEXT_PUBLIC_CLERK_SIGN_UP_URL}
              waitlistUrl={env.NEXT_PUBLIC_CLERK_WAITLIST_URL}
              signInFallbackRedirectUrl={signInFallbackRedirectUrl}
              signUpFallbackRedirectUrl={signUpFallbackRedirectUrl}
              signInForceRedirectUrl={signInForceRedirectUrl}
              signUpForceRedirectUrl={signUpForceRedirectUrl}
            >
              <AppLayoutContent>{children}</AppLayoutContent>
            </ClerkProviderWithNonce>
          </Suspense>
        ) : isAuthJsProvider ? (
          <SessionProvider>
            <Suspense fallback={<RootLayoutShell />}>
              <AppLayoutContent>{children}</AppLayoutContent>
            </Suspense>
          </SessionProvider>
        ) : (
          <AppLayoutContent>{children}</AppLayoutContent>
        )}
      </body>
    </html>
  );
}
