import { ClerkProvider } from '@clerk/nextjs';
import { SpeedInsights } from '@vercel/speed-insights/next';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { Suspense } from 'react';

import { env } from '@/core/env';

import { GlobalErrorHandlers } from '@/shared/components/error/global-error-handlers';

import { normalizeClerkPostAuthRedirect } from '@/modules/auth/lib/clerk-redirects';
import { HeaderWithAuth } from '@/modules/auth/ui/HeaderWithAuth';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function RootLayoutShell() {
  return (
    <header className="sticky top-0 z-50 w-full border-b border-zinc-200 bg-white/80 dark:border-zinc-800 dark:bg-black/80">
      <div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8">
        <div className="h-5 w-28 animate-pulse rounded bg-zinc-200 dark:bg-zinc-800" />
        <div className="h-9 w-20 animate-pulse rounded-full bg-zinc-100 dark:bg-zinc-800" />
      </div>
    </header>
  );
}

function AppLayoutContent({ children }: { children: React.ReactNode }) {
  return (
    <>
      <HeaderWithAuth />
      <GlobalErrorHandlers />
      {(env.VERCEL_ENV === 'production' || env.VERCEL_ENV === 'preview') && (
        <SpeedInsights />
      )}
      {children}
    </>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isClerkProvider = env.AUTH_PROVIDER === 'clerk';
  const signInFallbackRedirectUrl = normalizeClerkPostAuthRedirect(
    env.NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL,
    env.NEXT_PUBLIC_APP_URL,
  );
  const signUpFallbackRedirectUrl = normalizeClerkPostAuthRedirect(
    env.NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL,
    env.NEXT_PUBLIC_APP_URL,
  );
  const signInForceRedirectUrl = normalizeClerkPostAuthRedirect(
    env.NEXT_PUBLIC_CLERK_SIGN_IN_FORCE_REDIRECT_URL,
    env.NEXT_PUBLIC_APP_URL,
  );
  const signUpForceRedirectUrl = normalizeClerkPostAuthRedirect(
    env.NEXT_PUBLIC_CLERK_SIGN_UP_FORCE_REDIRECT_URL,
    env.NEXT_PUBLIC_APP_URL,
  );

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {isClerkProvider ? (
          <Suspense fallback={<RootLayoutShell />}>
            <ClerkProvider
              signInUrl={env.NEXT_PUBLIC_CLERK_SIGN_IN_URL}
              signUpUrl={env.NEXT_PUBLIC_CLERK_SIGN_UP_URL}
              waitlistUrl={env.NEXT_PUBLIC_CLERK_WAITLIST_URL}
              // Land on a stable app route after auth. Server guards own any
              // follow-up redirect into bootstrap or onboarding. Normalize
              // post-auth targets to absolute same-origin URLs for Clerk.
              signInFallbackRedirectUrl={signInFallbackRedirectUrl}
              signUpFallbackRedirectUrl={signUpFallbackRedirectUrl}
              signInForceRedirectUrl={signInForceRedirectUrl}
              signUpForceRedirectUrl={signUpForceRedirectUrl}
            >
              <AppLayoutContent>{children}</AppLayoutContent>
            </ClerkProvider>
          </Suspense>
        ) : (
          <AppLayoutContent>{children}</AppLayoutContent>
        )}
      </body>
    </html>
  );
}
