name: Lighthouse Performance

on:
  schedule:
    - cron: '0 0 * * 1' # Weekly on Mondays
  workflow_dispatch: # Allow manual trigger

jobs:
  performance-audit:
    name: Production Lighthouse Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # actions/checkout@v5

      - name: Run Lighthouse Audit
        uses: treosh/lighthouse-ci-action@3e7e23fb74242897f95c0ba9cabad3d0227b9b18 # treosh/lighthouse-ci-action@v12
        with:
          urls: |
            ${{ vars.PRODUCTION_URL }}
          uploadArtifacts: true
        env:
          LHCI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LHCI_TOKEN: ${{ secrets.LHCI_TOKEN }}
          LHCI_SERVER_BASE_URL: ${{ vars.LHCI_SERVER_BASE_URL }}
